"""
Export a Python-generated PLONK+FRI proof and circuit constants to a binary
format readable by the C verifier.

Run with the same field as your prover:
    ZKP_FIELD=babybear python3 export_to_c.py

Outputs:
    proof.bin       — binary proof (header + commits + openings + queries)
    circuit_data.c  — C source with selector and sigma polynomial coefficients

The C verifier in ../c_verifier reads proof.bin at runtime and links
circuit_data.c at compile time.

Binary format (little-endian throughout):
    HEADER (16 bytes):
        4   "PLNK"
        2   version (u16) = 1
        2   field_id (u16): 1=goldilocks, 2=babybear, 3=koalabear
        1   log_n (u8)
        1   log_blowup (u8)
        2   num_queries (u16)
        4   reserved (must be 0)

    COMMITS:    7 * 32 bytes
        a_root, b_root, c_root, Z_root, t_lo_root, t_mid_root, t_hi_root

    OPENINGS:   8 * elem_bytes (elem_bytes = 4 for BB/KB, 8 for Goldilocks)
        a(z), b(z), c(z), Z(z), Z(z*omega), t_lo(z), t_mid(z), t_hi(z)

    FRI_LAYER_ROOTS:    (log_N - 1) * 32 bytes
    FRI_FINAL_VALUE:    elem_bytes

    QUERIES (num_queries entries):
        q0                   u32 (4 bytes)
        f_openings (7x):
            v_lo, v_hi       2 * elem_bytes
            path_lo, path_hi 2 * log_N * 32 bytes
        Q_openings (log_N - 1 entries, layer i in 1..log_N-1):
            v_lo, v_hi       2 * elem_bytes
            path_lo, path_hi 2 * (log_N - i) * 32 bytes
"""

import os
import struct
import sys

# Make sure we use the same field as the prover.
# Default to BabyBear since that's the C verifier target.
os.environ.setdefault("ZKP_FIELD", "babybear")

import field
from demo import build_circuit, build_witness
from plonk import setup, prove


FIELD_IDS = {"goldilocks": 1, "babybear": 2, "koalabear": 3}
VERSION = 1


def elem_bytes_for_field():
    if field.FIELD_NAME == "goldilocks":
        return 8
    return 4  # BabyBear and KoalaBear are 31-bit, fit in 4 bytes


def pack_elem(v):
    eb = elem_bytes_for_field()
    return int(v).to_bytes(eb, "little")


def serialize_proof(proof, log_n, log_blowup, num_queries):
    log_N = log_n + log_blowup
    out = bytearray()

    # ---- Header ----
    out += b"PLNK"
    out += struct.pack("<H", VERSION)
    out += struct.pack("<H", FIELD_IDS[field.FIELD_NAME])
    out += struct.pack("<BB", log_n, log_blowup)
    out += struct.pack("<H", num_queries)
    out += b"\x00\x00\x00\x00"  # reserved

    # ---- Commits ----
    for k in ("a", "b", "c", "Z", "t_lo", "t_mid", "t_hi"):
        out += proof["commits"][k]
        assert len(proof["commits"][k]) == 32

    # ---- Openings ----
    for k in ("a", "b", "c", "Z", "Zw", "t_lo", "t_mid", "t_hi"):
        out += pack_elem(proof["openings"][k])

    # ---- FRI layer roots ----
    Q_roots = proof["fri"]["Q_layer_roots"]
    expected_layers = log_N - 1
    assert len(Q_roots) == expected_layers, "Q_layer_roots has {} entries, expected {}".format(
        len(Q_roots), expected_layers
    )
    for root in Q_roots:
        out += root
        assert len(root) == 32

    # ---- FRI final value ----
    out += pack_elem(proof["fri"]["final_value"])

    # ---- Queries ----
    queries = proof["fri"]["queries"]
    assert len(queries) == num_queries
    for q in queries:
        out += struct.pack("<I", q["q0"])

        f_openings = q["f_openings"]
        assert len(f_openings) == 7
        # First: all v_lo, v_hi pairs grouped together
        for opn in f_openings:
            out += pack_elem(opn["v_lo"])
            out += pack_elem(opn["v_hi"])
        # Then: all paths for all polys
        for opn in f_openings:
            assert len(opn["path_lo"]) == log_N
            assert len(opn["path_hi"]) == log_N
            for h in opn["path_lo"]:
                out += h
                assert len(h) == 32
            for h in opn["path_hi"]:
                out += h
                assert len(h) == 32

        # Q_openings: log_N - 1 layers, layer i has path length log_N - i
        Q_openings = q["Q_openings"]
        assert len(Q_openings) == expected_layers
        for i, opn in enumerate(Q_openings):
            layer = i + 1
            expected_path_len = log_N - layer
            out += pack_elem(opn["v_lo"])
            out += pack_elem(opn["v_hi"])
            assert len(opn["path_lo"]) == expected_path_len
            assert len(opn["path_hi"]) == expected_path_len
            for h in opn["path_lo"]:
                out += h
            for h in opn["path_hi"]:
                out += h

    return bytes(out)


def emit_c_circuit_data(pp, out_path):
    """Write the circuit constants (selectors, sigma polys, omega) as a C source file."""
    n = pp["n"]
    selectors = pp["selectors"]

    lines = []
    lines.append("/* Auto-generated by export_to_c.py. Do not edit. */\n")
    lines.append("#include <stdint.h>\n")
    lines.append("#include \"circuit_data.h\"\n\n")
    lines.append("/* Field: {} (p = {}) */\n".format(field.FIELD_NAME, field.P))
    lines.append("const uint32_t circuit_field_p     = {}u;\n".format(field.P))
    lines.append("const uint32_t circuit_mult_gen    = {}u;\n".format(field.MULT_GEN))
    lines.append("const uint32_t circuit_two_adic_gen = {}u;\n".format(field.TWO_ADIC_GEN))
    lines.append("const uint8_t  circuit_two_adicity = {};\n".format(field.TWO_ADICITY))
    lines.append("const uint32_t circuit_k1 = {}u;\n".format(field.K1))
    lines.append("const uint32_t circuit_k2 = {}u;\n".format(field.K2))
    lines.append("const uint8_t  circuit_log_n = {};\n".format(pp["log_n"]))
    lines.append("const uint8_t  circuit_n     = {};\n\n".format(n))

    def emit_array(name, vals):
        lines.append("const uint32_t {}[{}] = {{\n    ".format(name, len(vals)))
        lines.append(", ".join("{}u".format(int(v)) for v in vals))
        lines.append("\n};\n\n")

    emit_array("circuit_qL", selectors["q_L"])
    emit_array("circuit_qR", selectors["q_R"])
    emit_array("circuit_qO", selectors["q_O"])
    emit_array("circuit_qM", selectors["q_M"])
    emit_array("circuit_qC", selectors["q_C"])
    emit_array("circuit_S1", pp["S1"])
    emit_array("circuit_S2", pp["S2"])
    emit_array("circuit_S3", pp["S3"])

    with open(out_path, "w") as f:
        f.write("".join(lines))


def emit_c_header(pp, out_path):
    with open(out_path, "w") as f:
        f.write("""/* Auto-generated by export_to_c.py. Do not edit. */
#ifndef CIRCUIT_DATA_H
#define CIRCUIT_DATA_H

#include <stdint.h>

extern const uint32_t circuit_field_p;
extern const uint32_t circuit_mult_gen;
extern const uint32_t circuit_two_adic_gen;
extern const uint8_t  circuit_two_adicity;
extern const uint32_t circuit_k1;
extern const uint32_t circuit_k2;
extern const uint8_t  circuit_log_n;
extern const uint8_t  circuit_n;

extern const uint32_t circuit_qL[];
extern const uint32_t circuit_qR[];
extern const uint32_t circuit_qO[];
extern const uint32_t circuit_qM[];
extern const uint32_t circuit_qC[];
extern const uint32_t circuit_S1[];
extern const uint32_t circuit_S2[];
extern const uint32_t circuit_S3[];

#endif
""")


def main():
    out_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "legacy", "c_verifier")
    out_dir = os.path.normpath(out_dir)
    os.makedirs(out_dir, exist_ok=True)

    print("Field:", field.FIELD_NAME, "(p =", field.P, ")")
    if field.FIELD_NAME != "babybear":
        print("WARNING: C verifier currently only supports BabyBear. "
              "Re-run with ZKP_FIELD=babybear.")

    circuit = build_circuit()
    witness = build_witness(3)
    pp = setup(circuit)
    print("Setup OK; n =", pp["n"])

    print("Proving...")
    proof = prove(pp, witness)

    from fri import NUM_QUERIES, LOG_BLOWUP
    data = serialize_proof(proof, pp["log_n"], LOG_BLOWUP, NUM_QUERIES)

    proof_path = os.path.join(out_dir, "proof.bin")
    with open(proof_path, "wb") as f:
        f.write(data)
    print("Wrote", proof_path, "({} bytes)".format(len(data)))

    circuit_c = os.path.join(out_dir, "circuit_data.c")
    circuit_h = os.path.join(out_dir, "circuit_data.h")
    emit_c_circuit_data(pp, circuit_c)
    emit_c_header(pp, circuit_h)
    print("Wrote", circuit_c, "and", circuit_h)

    # Self-verify on Python side too, just to be sure
    from plonk import verify
    assert verify(pp, proof), "Python verifier rejected our own proof — aborting export"
    print("Python verifier OK on the same proof; safe to ship to C.")


if __name__ == "__main__":
    main()
